# Generated by Django 5.0 on 2024-01-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_img_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='./templates/Untitled.png', upload_to='images/'),
        ),
    ]
